Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

stuetzen = list(range(2, 1000 // 10 + 2))
kosten = []
for s in stuetzen:
    k, _, _ = Kosten(s)
    kosten.append(k)

plt.figure(figsize=(8,4))
plt.plot(stuetzen, kosten, ".")
plt.semilogy()
plt.title(label="Kostenentwicklung")
plt.xlabel("Anzahl StÃ¼tzen")
plt.ylabel("Kosten [â‚¬]")
plt.ylim(10**5, 10**7)
plt.xlim(0, 1000 // 10 + 2)
plt.grid(which = "both")
plt.xticks(range(0, 1000 // 10 + 2, 5))
plt.savefig("zusatz_photos/Seil_Kosten.svg")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 6[0m
[1;32m      4[0m kosten [38;5;241m=[39m []
[1;32m      5[0m [38;5;28;01mfor[39;00m s [38;5;129;01min[39;00m stuetzen:
[0;32m----> 6[0m     k, _, _ [38;5;241m=[39m [43mKosten[49m(s)
[1;32m      7[0m     kosten[38;5;241m.[39mappend(k)
[1;32m      9[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m8[39m,[38;5;241m4[39m))

[0;31mNameError[0m: name 'Kosten' is not defined

